name: Node CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Load 1Password Secrets
        uses: 1password/load-secrets-action@581a835fb51b8e7ec56b71cf2ffddd7e68bb25e0 # v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SHT_NPM_TOKEN: '${{ secrets.SECRETS_VAULT_ID }}/ozrgpobr7rqqgg4inmqqurfgfy/SHT_NPM_TOKEN'
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - uses: straw-hat-team/github-actions-workflows/nodejs/setup@5ab906d801d41b723636b498e57509e18db1856a # v1.9.1
      - shell: sh
        run: pnpm install --frozen-lockfile
        env:
          SHT_NPM_TOKEN: ${{ env.SHT_NPM_TOKEN }}
      - shell: sh
        run: pnpm turbo:build
        env:
          SHT_NPM_TOKEN: ${{ env.SHT_NPM_TOKEN }}
      - shell: sh
        run: pnpm turbo:test:vitest
        env:
          SHT_NPM_TOKEN: ${{ env.SHT_NPM_TOKEN }}

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Load 1Password Secrets
        uses: 1password/load-secrets-action@581a835fb51b8e7ec56b71cf2ffddd7e68bb25e0 # v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SHT_NPM_TOKEN: '${{ secrets.SECRETS_VAULT_ID }}/ozrgpobr7rqqgg4inmqqurfgfy/SHT_NPM_TOKEN'
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - uses: straw-hat-team/github-actions-workflows/nodejs/setup@5ab906d801d41b723636b498e57509e18db1856a # v1.9.1
      - shell: sh
        run: pnpm install --frozen-lockfile
        env:
          SHT_NPM_TOKEN: ${{ env.SHT_NPM_TOKEN }}
      - shell: sh
        run: pnpm exec prettier --check */** --ignore-unknown --no-error-on-unmatched-pattern
        env:
          SHT_NPM_TOKEN: ${{ env.SHT_NPM_TOKEN }}
